/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace hero {
    export interface HeroService {
        findOne(
            data: HeroById,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Hero>;
        findMany(
            data: Observable<HeroById>,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Hero>;
    }
    export interface HeroById {
        id: string;
    }
    // Default is [required]
    // Optional adds the [?] operator
    export interface Hero {
        id: string;
        name?: string;
    }
}

